using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Compositor_korean_win.Shell;

/// <summary>The slice of the Win32 API the shell needs to own a window.</summary>
/// <remarks>
/// Hand-bound rather than taken from a wrapper package, because the shell's whole argument is that
/// it adds nothing to the binary. Every entry point here is source-generated by
/// <c>[LibraryImport]</c>, so none of it needs reflection at run time.
/// </remarks>
internal static unsafe partial class Win32
{
    internal const uint WS_OVERLAPPEDWINDOW = 0x00CF0000;
    internal const uint WS_VISIBLE = 0x10000000;
    internal const int SW_SHOW = 5;
    internal const int SW_HIDE = 0;

    internal const uint WM_DESTROY = 0x0002;
    internal const uint WM_SIZE = 0x0005;
    internal const uint WM_PAINT = 0x000F;
    internal const uint WM_CLOSE = 0x0010;
    internal const uint WM_ERASEBKGND = 0x0014;
    internal const uint WM_KEYDOWN = 0x0100;
    internal const uint WM_KEYUP = 0x0101;
    internal const uint WM_DPICHANGED = 0x02E0;

    internal const uint WM_MOUSEMOVE = 0x0200;
    internal const uint WM_LBUTTONDOWN = 0x0201;
    internal const uint WM_LBUTTONUP = 0x0202;
    internal const uint WM_RBUTTONDOWN = 0x0204;
    internal const uint WM_RBUTTONUP = 0x0205;
    internal const uint WM_MBUTTONDOWN = 0x0207;
    internal const uint WM_MBUTTONUP = 0x0208;
    internal const uint WM_MOUSEWHEEL = 0x020A;
    internal const uint WM_CAPTURECHANGED = 0x0215;

    internal const int VK_ESCAPE = 0x1B;
    internal const int VK_RETURN = 0x0D;
    internal const int VK_SPACE = 0x20;
    internal const int VK_SHIFT = 0x10;
    internal const int VK_CONTROL = 0x11;
    internal const int VK_MENU = 0x12;
    internal const int VK_LEFT = 0x25;
    internal const int VK_UP = 0x26;
    internal const int VK_RIGHT = 0x27;
    internal const int VK_DOWN = 0x28;
    internal const int VK_0 = 0x30;
    internal const int VK_1 = 0x31;
    internal const int VK_NUMPAD0 = 0x60;
    internal const int VK_NUMPAD9 = 0x69;
    internal const int VK_A = 0x41;
    internal const int VK_B = 0x42;
    internal const int VK_D = 0x44;
    internal const int VK_E = 0x45;
    internal const int VK_G = 0x47;
    internal const int VK_J = 0x4A;
    internal const int VK_L = 0x4C;
    internal const int VK_M = 0x4D;
    internal const int VK_R = 0x52;
    internal const int VK_S = 0x53;
    internal const int VK_U = 0x55;
    internal const int VK_V = 0x56;
    internal const int VK_W = 0x57;
    internal const int VK_Y = 0x59;
    internal const int VK_Z = 0x5A;
    internal const int VK_N = 0x4E;
    internal const int VK_O = 0x4F;
    internal const int VK_P = 0x50;
    internal const int VK_Q = 0x51;
    internal const int VK_OEM_PLUS = 0xBB;
    internal const int VK_OEM_MINUS = 0xBD;
    internal const int VK_ADD = 0x6B;
    internal const int VK_SUBTRACT = 0x6D;

    /// <summary>The bracket keys, which size the brush.</summary>
    internal const int VK_OEM_4 = 0xDB;
    internal const int VK_OEM_6 = 0xDD;

    /// <summary>The wheel's own unit: one notch.</summary>
    internal const int WHEEL_DELTA = 120;

    internal const uint CS_HREDRAW = 0x0002;
    internal const uint CS_VREDRAW = 0x0001;

    internal const int IDC_ARROW = 32512;

    [StructLayout(LayoutKind.Sequential)]
    internal struct WNDCLASSEXW
    {
        public uint cbSize;
        public uint style;
        public nint lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public nint hInstance;
        public nint hIcon;
        public nint hCursor;
        public nint hbrBackground;
        public nint lpszMenuName;
        public nint lpszClassName;
        public nint hIconSm;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct MSG
    {
        public nint hwnd;
        public uint message;
        public nuint wParam;
        public nint lParam;
        public uint time;
        public int ptX;
        public int ptY;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct RECT
    {
        public int Left, Top, Right, Bottom;
        public readonly int Width => Right - Left;
        public readonly int Height => Bottom - Top;
    }

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial ushort RegisterClassExW(in WNDCLASSEXW windowClass);

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint CreateWindowExW(
        uint exStyle, string className, string windowName, uint style,
        int x, int y, int width, int height,
        nint parent, nint menu, nint instance, nint param);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyWindow(nint hwnd);

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool SetWindowTextW(nint hwnd, string text);

    // Menus.

    internal const uint WM_COMMAND = 0x0111;
    internal const uint WM_INITMENUPOPUP = 0x0117;
    internal const uint WM_SYSKEYDOWN = 0x0104;

    internal const uint MF_STRING = 0x0000;
    internal const uint MF_GRAYED = 0x0001;
    internal const uint MF_CHECKED = 0x0008;
    internal const uint MF_POPUP = 0x0010;
    internal const uint MF_SEPARATOR = 0x0800;
    internal const uint MF_BYCOMMAND = 0x0000;
    internal const uint MF_BYPOSITION = 0x0400;
    internal const uint MF_ENABLED = 0x0000;
    internal const uint MF_UNCHECKED = 0x0000;

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint CreateMenu();

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint CreatePopupMenu();

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool AppendMenuW(nint menu, uint flags, nuint idOrPopup, string? text);

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ModifyMenuW(nint menu, uint position, uint flags, nuint idOrPopup, string? text);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool SetMenu(nint hwnd, nint menu);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DrawMenuBar(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyMenu(nint menu);

    [LibraryImport("user32.dll")]
    internal static partial int EnableMenuItem(nint menu, uint item, uint enable);

    [LibraryImport("user32.dll")]
    internal static partial uint CheckMenuItem(nint menu, uint item, uint check);

    [LibraryImport("user32.dll")]
    internal static partial int GetMenuItemCount(nint menu);

    [LibraryImport("user32.dll")]
    internal static partial nint GetSubMenu(nint menu, int position);

    [LibraryImport("user32.dll")]
    internal static partial uint GetMenuItemID(nint menu, int position);

    [LibraryImport("user32.dll", EntryPoint = "GetMenuStringW")]
    internal static partial int GetMenuStringW(nint menu, uint item, char* text, int max, uint flags);

    [LibraryImport("user32.dll")]
    internal static partial uint GetMenuState(nint menu, uint item, uint flags);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint SendMessageW(nint hwnd, uint message, nuint wParam, nint lParam);

    // Message boxes and the common file dialogs.

    internal const uint MB_OK = 0x0000;
    internal const uint MB_YESNOCANCEL = 0x0003;
    internal const uint MB_ICONWARNING = 0x0030;
    internal const int IDCANCEL = 2;
    internal const int IDYES = 6;
    internal const int IDNO = 7;
    internal const uint OFN_ALLOWMULTISELECT = 0x00000200;
    internal const uint MB_ICONERROR = 0x0010;
    internal const uint MB_ICONINFORMATION = 0x0040;

    [LibraryImport("user32.dll", StringMarshalling = StringMarshalling.Utf16)]
    internal static partial int MessageBoxW(nint hwnd, string text, string caption, uint type);

    internal const uint OFN_OVERWRITEPROMPT = 0x00000002;
    internal const uint OFN_NOCHANGEDIR = 0x00000008;
    internal const uint OFN_PATHMUSTEXIST = 0x00000800;
    internal const uint OFN_FILEMUSTEXIST = 0x00001000;
    internal const uint OFN_EXPLORER = 0x00080000;

    [StructLayout(LayoutKind.Sequential)]
    internal struct OPENFILENAMEW
    {
        public uint lStructSize;
        public nint hwndOwner;
        public nint hInstance;
        public char* lpstrFilter;
        public char* lpstrCustomFilter;
        public uint nMaxCustFilter;
        public uint nFilterIndex;
        public char* lpstrFile;
        public uint nMaxFile;
        public char* lpstrFileTitle;
        public uint nMaxFileTitle;
        public char* lpstrInitialDir;
        public char* lpstrTitle;
        public uint Flags;
        public ushort nFileOffset;
        public ushort nFileExtension;
        public char* lpstrDefExt;
        public nint lCustData;
        public nint lpfnHook;
        public char* lpTemplateName;
        public nint pvReserved;
        public uint dwReserved;
        public uint FlagsEx;
    }

    [LibraryImport("comdlg32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetOpenFileNameW(ref OPENFILENAMEW dialog);

    [LibraryImport("comdlg32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetSaveFileNameW(ref OPENFILENAMEW dialog);

    // Pop-up menus, the colour dialog, the rename box and timers, for the panels.

    internal const uint TPM_RETURNCMD = 0x0100;
    internal const uint TPM_NONOTIFY = 0x0080;
    internal const uint WM_TIMER = 0x0113;
    internal const uint WM_SETFONT = 0x0030;
    internal const uint WM_LBUTTONDBLCLK = 0x0203;
    internal const uint CS_DBLCLKS = 0x0008;
    internal const uint EM_SETSEL = 0x00B1;
    internal const uint WS_CHILD = 0x40000000;
    internal const uint WS_BORDER = 0x00800000;
    internal const uint ES_AUTOHSCROLL = 0x0080;

    [StructLayout(LayoutKind.Sequential)]
    internal struct POINTSTRUCT
    {
        public int X, Y;
    }

    [LibraryImport("user32.dll")]
    internal static partial int TrackPopupMenuEx(nint menu, uint flags, int x, int y, nint hwnd, nint parameters);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ClientToScreen(nint hwnd, ref POINTSTRUCT point);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetCursorPos(out POINTSTRUCT point);

    [LibraryImport("user32.dll")]
    internal static partial nuint SetTimer(nint hwnd, nuint id, uint milliseconds, nint callback);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool KillTimer(nint hwnd, nuint id);

    [LibraryImport("user32.dll")]
    internal static partial nint SetFocus(nint hwnd);

    [LibraryImport("user32.dll", EntryPoint = "GetWindowTextW")]
    internal static partial int GetWindowTextW(nint hwnd, char* text, int max);

    [LibraryImport("gdi32.dll", StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint CreateFontW(int height, int width, int escapement, int orientation, int weight,
                                             uint italic, uint underline, uint strikeOut, uint charSet,
                                             uint outPrecision, uint clipPrecision, uint quality,
                                             uint pitchAndFamily, string face);

    [LibraryImport("gdi32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DeleteObject(nint handle);

    internal const uint CC_RGBINIT = 0x0001;
    internal const uint CC_FULLOPEN = 0x0002;

    [StructLayout(LayoutKind.Sequential)]
    internal struct CHOOSECOLORW
    {
        public uint lStructSize;
        public nint hwndOwner;
        public nint hInstance;
        public uint rgbResult;
        public uint* lpCustColors;
        public uint Flags;
        public nint lCustData;
        public nint lpfnHook;
        public nint lpTemplateName;
    }

    [LibraryImport("comdlg32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ChooseColorW(ref CHOOSECOLORW dialog);

    /// <summary>DirectWrite's factory; type 0 is shared.</summary>
    [LibraryImport("dwrite.dll")]
    internal static partial int DWriteCreateFactory(int factoryType, in Guid iid, out nint factory);

    // The clipboard.

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool OpenClipboard(nint owner);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool CloseClipboard();

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool EmptyClipboard();

    [LibraryImport("user32.dll")]
    internal static partial nint SetClipboardData(uint format, nint memory);

    [LibraryImport("user32.dll")]
    internal static partial nint GetClipboardData(uint format);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool IsClipboardFormatAvailable(uint format);

    [LibraryImport("user32.dll", StringMarshalling = StringMarshalling.Utf16)]
    internal static partial uint RegisterClipboardFormatW(string name);

    [LibraryImport("user32.dll")]
    internal static partial uint GetClipboardSequenceNumber();

    [LibraryImport("kernel32.dll")]
    internal static partial nint GlobalAlloc(uint flags, nuint bytes);

    [LibraryImport("kernel32.dll")]
    internal static partial nint GlobalLock(nint memory);

    [LibraryImport("kernel32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GlobalUnlock(nint memory);

    [LibraryImport("kernel32.dll")]
    internal static partial nuint GlobalSize(nint memory);

    [LibraryImport("kernel32.dll")]
    internal static partial nint GlobalFree(nint memory);

    internal const int VK_BACK = 0x08;
    internal const int VK_TAB = 0x09;
    internal const uint WM_DROPFILES = 0x0233;

    [LibraryImport("shell32.dll")]
    internal static partial void DragAcceptFiles(nint window, [MarshalAs(UnmanagedType.Bool)] bool accept);

    [LibraryImport("shell32.dll")]
    internal static unsafe partial uint DragQueryFileW(nint drop, uint index, char* file, uint length);

    [LibraryImport("shell32.dll")]
    internal static partial void DragFinish(nint drop);

    [LibraryImport("ole32.dll")]
    internal static partial int OleInitialize(nint reserved);

    [LibraryImport("ole32.dll")]
    internal static partial void OleUninitialize();

    [LibraryImport("ole32.dll")]
    internal static partial int RegisterDragDrop(nint window, IOleDropTarget target);

    [LibraryImport("ole32.dll")]
    internal static partial int RevokeDragDrop(nint window);

    [LibraryImport("ole32.dll")]
    internal static partial void ReleaseStgMedium(in StorageMedium medium);
    internal const uint WM_CHAR = 0x0102;
    internal const int VK_DELETE = 0x2E;
    internal const int VK_C = 0x43;
    internal const int VK_T = 0x54;
    internal const int VK_H = 0x48;
    internal const int VK_I = 0x49;
    internal const int VK_X = 0x58;

    /// <summary>The language the user reads Windows in, as a LANGID.</summary>
    [LibraryImport("kernel32.dll")]
    internal static partial ushort GetUserDefaultUILanguage();

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ShowWindow(nint hwnd, int command);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool UpdateWindow(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetClientRect(nint hwnd, out RECT rect);

    [LibraryImport("user32.dll")]
    internal static partial nint DefWindowProcW(nint hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool PeekMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax, uint remove);

    [LibraryImport("user32.dll")]
    internal static partial int GetMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool TranslateMessage(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial nint DispatchMessageW(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial void PostQuitMessage(int exitCode);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint LoadCursorW(nint instance, nint cursorName);

    /// <summary>The exe's own icon: the SDK writes ApplicationIcon as group 32512.</summary>
    internal const nint ApplicationIconId = 32512;

    internal const uint MB_YESNO = 0x0004;
    internal const int SW_SHOWNORMAL = 1;

    // WinINet, for Help > Check for Updates (Updates.Fetch).
    internal const uint INTERNET_OPEN_TYPE_PRECONFIG = 0;
    internal const uint INTERNET_OPTION_CONNECT_TIMEOUT = 2;
    internal const uint INTERNET_OPTION_RECEIVE_TIMEOUT = 6;
    internal const uint INTERNET_FLAG_RELOAD = 0x80000000;
    internal const uint INTERNET_FLAG_NO_CACHE_WRITE = 0x04000000;
    internal const uint INTERNET_FLAG_SECURE = 0x00800000;

    [LibraryImport("wininet.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint InternetOpenW(string agent, uint accessType, string? proxy, string? bypass, uint flags);

    [LibraryImport("wininet.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint InternetOpenUrlW(nint session, string url, string? headers, uint headersLength,
                                                  uint flags, nint context);

    [LibraryImport("wininet.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool InternetReadFile(nint file, byte* buffer, uint toRead, out uint read);

    [LibraryImport("wininet.dll", SetLastError = true, EntryPoint = "InternetSetOptionW")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool InternetSetOptionW(nint handle, uint option, void* buffer, uint length);

    [LibraryImport("wininet.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool InternetCloseHandle(nint handle);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint LoadIconW(nint instance, nint iconName);

    [LibraryImport("shell32.dll", StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint ShellExecuteW(nint window, string? operation, string file, string? parameters,
                                               string? directory, int show);

    [LibraryImport("user32.dll")]
    internal static partial uint GetDpiForWindow(nint hwnd);

    [StructLayout(LayoutKind.Sequential)]
    internal struct POINT
    {
        public int X;
        public int Y;
    }

    /// <summary>The wheel reports where the pointer is on the desktop, not in the window.</summary>
    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ScreenToClient(nint hwnd, ref POINT point);

    [LibraryImport("user32.dll")]
    internal static partial nint SetCapture(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ReleaseCapture();

    [LibraryImport("user32.dll")]
    internal static partial short GetKeyState(int key);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool InvalidateRect(nint hwnd, nint rect, [MarshalAs(UnmanagedType.Bool)] bool erase);

    /// <summary>Whether a modifier is down right now, as the mouse messages do not carry all of them.</summary>
    internal static bool IsKeyDown(int key) => (GetKeyState(key) & 0x8000) != 0;

    /// <summary>The x of a mouse message's packed position, which is signed.</summary>
    internal static int PositionX(nint lParam) => (short)(lParam & 0xFFFF);

    internal static int PositionY(nint lParam) => (short)((lParam >> 16) & 0xFFFF);

    /// <summary>The wheel's rotation, in the high word of wParam and signed.</summary>
    internal static int WheelDelta(nuint wParam) => (short)((wParam >> 16) & 0xFFFF);

    [LibraryImport("kernel32.dll")]
    internal static partial nint GetModuleHandleW(nint moduleName);

    internal const uint PM_REMOVE = 0x0001;
    internal const uint WM_QUIT = 0x0012;

    /// <summary>
    /// How long this process has been alive, measured from when Windows created it.
    /// </summary>
    /// <remarks>
    /// Taken from the kernel rather than from a timestamp in Main, because a good part of what M0
    /// is measuring — the whole argument for NativeAOT over a framework-dependent build — happens
    /// before the first managed line runs.
    /// </remarks>
    internal static TimeSpan ProcessUptime()
    {
        if (!GetProcessTimes(GetCurrentProcess(), out long created, out _, out _, out _))
            return TimeSpan.Zero;

        // Both are FILETIME: 100-nanosecond ticks since 1601-01-01, which is also DateTime's tick
        // unit, so the difference needs no conversion.
        return TimeSpan.FromTicks(DateTime.UtcNow.ToFileTimeUtc() - created);
    }

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessTimes(nint process, out long creation, out long exit,
                                                out long kernel, out long user);

    /// <summary>Peak working set in bytes, for the memory figure M0 reports.</summary>
    internal static long PeakWorkingSet()
    {
        var counters = new PROCESS_MEMORY_COUNTERS { cb = (uint)Unsafe.SizeOf<PROCESS_MEMORY_COUNTERS>() };
        return GetProcessMemoryInfo(GetCurrentProcess(), ref counters, counters.cb)
            ? (long)counters.PeakWorkingSetSize
            : 0;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct PROCESS_MEMORY_COUNTERS
    {
        public uint cb;
        public uint PageFaultCount;
        public nuint PeakWorkingSetSize;
        public nuint WorkingSetSize;
        public nuint QuotaPeakPagedPoolUsage;
        public nuint QuotaPagedPoolUsage;
        public nuint QuotaPeakNonPagedPoolUsage;
        public nuint QuotaNonPagedPoolUsage;
        public nuint PagefileUsage;
        public nuint PeakPagefileUsage;
    }

    [LibraryImport("kernel32.dll")]
    private static partial nint GetCurrentProcess();

    [LibraryImport("psapi.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessMemoryInfo(nint process, ref PROCESS_MEMORY_COUNTERS counters, uint size);
}
