using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Compositor_korean_win.Shell;

/// <summary>The slice of the Win32 API the shell needs to own a window.</summary>
/// <remarks>
/// Hand-bound rather than taken from a wrapper package, because the shell's whole argument is that
/// it adds nothing to the binary. Every entry point here is source-generated by
/// <c>[LibraryImport]</c>, so none of it needs reflection at run time.
/// </remarks>
internal static partial class Win32
{
    internal const uint WS_OVERLAPPEDWINDOW = 0x00CF0000;
    internal const uint WS_VISIBLE = 0x10000000;
    internal const int SW_SHOW = 5;
    internal const int SW_HIDE = 0;

    internal const uint WM_DESTROY = 0x0002;
    internal const uint WM_SIZE = 0x0005;
    internal const uint WM_PAINT = 0x000F;
    internal const uint WM_CLOSE = 0x0010;
    internal const uint WM_ERASEBKGND = 0x0014;
    internal const uint WM_KEYDOWN = 0x0100;
    internal const uint WM_DPICHANGED = 0x02E0;

    internal const int VK_ESCAPE = 0x1B;

    internal const uint CS_HREDRAW = 0x0002;
    internal const uint CS_VREDRAW = 0x0001;

    internal const int IDC_ARROW = 32512;

    [StructLayout(LayoutKind.Sequential)]
    internal struct WNDCLASSEXW
    {
        public uint cbSize;
        public uint style;
        public nint lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public nint hInstance;
        public nint hIcon;
        public nint hCursor;
        public nint hbrBackground;
        public nint lpszMenuName;
        public nint lpszClassName;
        public nint hIconSm;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct MSG
    {
        public nint hwnd;
        public uint message;
        public nuint wParam;
        public nint lParam;
        public uint time;
        public int ptX;
        public int ptY;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct RECT
    {
        public int Left, Top, Right, Bottom;
        public readonly int Width => Right - Left;
        public readonly int Height => Bottom - Top;
    }

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial ushort RegisterClassExW(in WNDCLASSEXW windowClass);

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint CreateWindowExW(
        uint exStyle, string className, string windowName, uint style,
        int x, int y, int width, int height,
        nint parent, nint menu, nint instance, nint param);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyWindow(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ShowWindow(nint hwnd, int command);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool UpdateWindow(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetClientRect(nint hwnd, out RECT rect);

    [LibraryImport("user32.dll")]
    internal static partial nint DefWindowProcW(nint hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool PeekMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax, uint remove);

    [LibraryImport("user32.dll")]
    internal static partial int GetMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool TranslateMessage(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial nint DispatchMessageW(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial void PostQuitMessage(int exitCode);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint LoadCursorW(nint instance, nint cursorName);

    [LibraryImport("user32.dll")]
    internal static partial uint GetDpiForWindow(nint hwnd);

    [LibraryImport("kernel32.dll")]
    internal static partial nint GetModuleHandleW(nint moduleName);

    internal const uint PM_REMOVE = 0x0001;
    internal const uint WM_QUIT = 0x0012;

    /// <summary>
    /// How long this process has been alive, measured from when Windows created it.
    /// </summary>
    /// <remarks>
    /// Taken from the kernel rather than from a timestamp in Main, because a good part of what M0
    /// is measuring — the whole argument for NativeAOT over a framework-dependent build — happens
    /// before the first managed line runs.
    /// </remarks>
    internal static TimeSpan ProcessUptime()
    {
        if (!GetProcessTimes(GetCurrentProcess(), out long created, out _, out _, out _))
            return TimeSpan.Zero;

        // Both are FILETIME: 100-nanosecond ticks since 1601-01-01, which is also DateTime's tick
        // unit, so the difference needs no conversion.
        return TimeSpan.FromTicks(DateTime.UtcNow.ToFileTimeUtc() - created);
    }

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessTimes(nint process, out long creation, out long exit,
                                                out long kernel, out long user);

    /// <summary>Peak working set in bytes, for the memory figure M0 reports.</summary>
    internal static long PeakWorkingSet()
    {
        var counters = new PROCESS_MEMORY_COUNTERS { cb = (uint)Unsafe.SizeOf<PROCESS_MEMORY_COUNTERS>() };
        return GetProcessMemoryInfo(GetCurrentProcess(), ref counters, counters.cb)
            ? (long)counters.PeakWorkingSetSize
            : 0;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct PROCESS_MEMORY_COUNTERS
    {
        public uint cb;
        public uint PageFaultCount;
        public nuint PeakWorkingSetSize;
        public nuint WorkingSetSize;
        public nuint QuotaPeakPagedPoolUsage;
        public nuint QuotaPagedPoolUsage;
        public nuint QuotaPeakNonPagedPoolUsage;
        public nuint QuotaNonPagedPoolUsage;
        public nuint PagefileUsage;
        public nuint PeakPagefileUsage;
    }

    [LibraryImport("kernel32.dll")]
    private static partial nint GetCurrentProcess();

    [LibraryImport("psapi.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessMemoryInfo(nint process, ref PROCESS_MEMORY_COUNTERS counters, uint size);
}
