using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Compositor_korean_win.Shell;

/// <summary>The slice of the Win32 API the shell needs to own a window.</summary>
/// <remarks>
/// Hand-bound rather than taken from a wrapper package, because the shell's whole argument is that
/// it adds nothing to the binary. Every entry point here is source-generated by
/// <c>[LibraryImport]</c>, so none of it needs reflection at run time.
/// </remarks>
internal static partial class Win32
{
    internal const uint WS_OVERLAPPEDWINDOW = 0x00CF0000;
    internal const uint WS_VISIBLE = 0x10000000;
    internal const int SW_SHOW = 5;
    internal const int SW_HIDE = 0;

    internal const uint WM_DESTROY = 0x0002;
    internal const uint WM_SIZE = 0x0005;
    internal const uint WM_PAINT = 0x000F;
    internal const uint WM_CLOSE = 0x0010;
    internal const uint WM_ERASEBKGND = 0x0014;
    internal const uint WM_KEYDOWN = 0x0100;
    internal const uint WM_KEYUP = 0x0101;
    internal const uint WM_DPICHANGED = 0x02E0;

    internal const uint WM_MOUSEMOVE = 0x0200;
    internal const uint WM_LBUTTONDOWN = 0x0201;
    internal const uint WM_LBUTTONUP = 0x0202;
    internal const uint WM_MBUTTONDOWN = 0x0207;
    internal const uint WM_MBUTTONUP = 0x0208;
    internal const uint WM_MOUSEWHEEL = 0x020A;
    internal const uint WM_CAPTURECHANGED = 0x0215;

    internal const int VK_ESCAPE = 0x1B;
    internal const int VK_RETURN = 0x0D;
    internal const int VK_SPACE = 0x20;
    internal const int VK_SHIFT = 0x10;
    internal const int VK_CONTROL = 0x11;
    internal const int VK_MENU = 0x12;
    internal const int VK_LEFT = 0x25;
    internal const int VK_UP = 0x26;
    internal const int VK_RIGHT = 0x27;
    internal const int VK_DOWN = 0x28;
    internal const int VK_0 = 0x30;
    internal const int VK_1 = 0x31;
    internal const int VK_A = 0x41;
    internal const int VK_B = 0x42;
    internal const int VK_D = 0x44;
    internal const int VK_E = 0x45;
    internal const int VK_G = 0x47;
    internal const int VK_J = 0x4A;
    internal const int VK_L = 0x4C;
    internal const int VK_M = 0x4D;
    internal const int VK_R = 0x52;
    internal const int VK_S = 0x53;
    internal const int VK_U = 0x55;
    internal const int VK_V = 0x56;
    internal const int VK_W = 0x57;
    internal const int VK_Y = 0x59;
    internal const int VK_Z = 0x5A;

    /// <summary>The bracket keys, which size the brush.</summary>
    internal const int VK_OEM_4 = 0xDB;
    internal const int VK_OEM_6 = 0xDD;

    /// <summary>Function keys, which open the adjustments and filters until M6 gives them menus.</summary>
    internal const int VK_F2 = 0x71;
    internal const int VK_F3 = 0x72;
    internal const int VK_F4 = 0x73;
    internal const int VK_F5 = 0x74;
    internal const int VK_F6 = 0x75;
    internal const int VK_F7 = 0x76;
    internal const int VK_F8 = 0x77;

    /// <summary>The wheel's own unit: one notch.</summary>
    internal const int WHEEL_DELTA = 120;

    internal const uint CS_HREDRAW = 0x0002;
    internal const uint CS_VREDRAW = 0x0001;

    internal const int IDC_ARROW = 32512;

    [StructLayout(LayoutKind.Sequential)]
    internal struct WNDCLASSEXW
    {
        public uint cbSize;
        public uint style;
        public nint lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public nint hInstance;
        public nint hIcon;
        public nint hCursor;
        public nint hbrBackground;
        public nint lpszMenuName;
        public nint lpszClassName;
        public nint hIconSm;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct MSG
    {
        public nint hwnd;
        public uint message;
        public nuint wParam;
        public nint lParam;
        public uint time;
        public int ptX;
        public int ptY;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct RECT
    {
        public int Left, Top, Right, Bottom;
        public readonly int Width => Right - Left;
        public readonly int Height => Bottom - Top;
    }

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial ushort RegisterClassExW(in WNDCLASSEXW windowClass);

    [LibraryImport("user32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    internal static partial nint CreateWindowExW(
        uint exStyle, string className, string windowName, uint style,
        int x, int y, int width, int height,
        nint parent, nint menu, nint instance, nint param);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyWindow(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ShowWindow(nint hwnd, int command);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool UpdateWindow(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetClientRect(nint hwnd, out RECT rect);

    [LibraryImport("user32.dll")]
    internal static partial nint DefWindowProcW(nint hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool PeekMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax, uint remove);

    [LibraryImport("user32.dll")]
    internal static partial int GetMessageW(out MSG message, nint hwnd, uint filterMin, uint filterMax);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool TranslateMessage(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial nint DispatchMessageW(in MSG message);

    [LibraryImport("user32.dll")]
    internal static partial void PostQuitMessage(int exitCode);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial nint LoadCursorW(nint instance, nint cursorName);

    [LibraryImport("user32.dll")]
    internal static partial uint GetDpiForWindow(nint hwnd);

    [StructLayout(LayoutKind.Sequential)]
    internal struct POINT
    {
        public int X;
        public int Y;
    }

    /// <summary>The wheel reports where the pointer is on the desktop, not in the window.</summary>
    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ScreenToClient(nint hwnd, ref POINT point);

    [LibraryImport("user32.dll")]
    internal static partial nint SetCapture(nint hwnd);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool ReleaseCapture();

    [LibraryImport("user32.dll")]
    internal static partial short GetKeyState(int key);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool InvalidateRect(nint hwnd, nint rect, [MarshalAs(UnmanagedType.Bool)] bool erase);

    /// <summary>Whether a modifier is down right now, as the mouse messages do not carry all of them.</summary>
    internal static bool IsKeyDown(int key) => (GetKeyState(key) & 0x8000) != 0;

    /// <summary>The x of a mouse message's packed position, which is signed.</summary>
    internal static int PositionX(nint lParam) => (short)(lParam & 0xFFFF);

    internal static int PositionY(nint lParam) => (short)((lParam >> 16) & 0xFFFF);

    /// <summary>The wheel's rotation, in the high word of wParam and signed.</summary>
    internal static int WheelDelta(nuint wParam) => (short)((wParam >> 16) & 0xFFFF);

    [LibraryImport("kernel32.dll")]
    internal static partial nint GetModuleHandleW(nint moduleName);

    internal const uint PM_REMOVE = 0x0001;
    internal const uint WM_QUIT = 0x0012;

    /// <summary>
    /// How long this process has been alive, measured from when Windows created it.
    /// </summary>
    /// <remarks>
    /// Taken from the kernel rather than from a timestamp in Main, because a good part of what M0
    /// is measuring — the whole argument for NativeAOT over a framework-dependent build — happens
    /// before the first managed line runs.
    /// </remarks>
    internal static TimeSpan ProcessUptime()
    {
        if (!GetProcessTimes(GetCurrentProcess(), out long created, out _, out _, out _))
            return TimeSpan.Zero;

        // Both are FILETIME: 100-nanosecond ticks since 1601-01-01, which is also DateTime's tick
        // unit, so the difference needs no conversion.
        return TimeSpan.FromTicks(DateTime.UtcNow.ToFileTimeUtc() - created);
    }

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessTimes(nint process, out long creation, out long exit,
                                                out long kernel, out long user);

    /// <summary>Peak working set in bytes, for the memory figure M0 reports.</summary>
    internal static long PeakWorkingSet()
    {
        var counters = new PROCESS_MEMORY_COUNTERS { cb = (uint)Unsafe.SizeOf<PROCESS_MEMORY_COUNTERS>() };
        return GetProcessMemoryInfo(GetCurrentProcess(), ref counters, counters.cb)
            ? (long)counters.PeakWorkingSetSize
            : 0;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct PROCESS_MEMORY_COUNTERS
    {
        public uint cb;
        public uint PageFaultCount;
        public nuint PeakWorkingSetSize;
        public nuint WorkingSetSize;
        public nuint QuotaPeakPagedPoolUsage;
        public nuint QuotaPagedPoolUsage;
        public nuint QuotaPeakNonPagedPoolUsage;
        public nuint QuotaNonPagedPoolUsage;
        public nuint PagefileUsage;
        public nuint PeakPagefileUsage;
    }

    [LibraryImport("kernel32.dll")]
    private static partial nint GetCurrentProcess();

    [LibraryImport("psapi.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool GetProcessMemoryInfo(nint process, ref PROCESS_MEMORY_COUNTERS counters, uint size);
}
