using System.Collections.Frozen;

namespace Compositor_korean_win.Core;

/// <summary>Everything the interface can say, one member per phrase.</summary>
public enum TextKey
{
    AppTitle,

    // Languages, each in its own words.
    LanguageEnglish,
    LanguageKorean,

    // Tools.
    ToolMove,
    ToolRectangleMarquee,
    ToolEllipseMarquee,
    ToolLasso,
    ToolPolygonLasso,
    ToolBrush,
    ToolEraser,
    ToolCloneStamp,
    ToolBlur,
    ToolHeal,
    ToolMagicWand,
    ToolGradient,
    ToolShape,

    // Adjustments, as the Image menu and the adjustment layers name them.
    AdjustLevels,
    AdjustCurves,
    AdjustHueSaturation,
    AdjustExposure,
    AdjustGradientMap,
    AdjustGrain,

    // Filters.
    FilterGaussianBlur,
    FilterMotionBlur,
    FilterAddNoise,
    FilterLensCorrection,

    // History steps and the names new layers are given.
    HistoryEdit,
    HistoryDuplicateLayer,
    HistoryMoveLayer,
    HistoryTransformLayer,
    HistoryMoveSelection,
    HistoryDuplicateSelection,
    HistoryAdjustmentLayer,
    LayerCopyName,

    // The menu bar. An ampersand marks the letter Alt reaches the item by.
    MenuFile,
    MenuEdit,
    MenuImage,
    MenuLayer,
    MenuSelect,
    MenuFilter,
    MenuView,
    MenuHelp,
    MenuAdjustments,
    MenuNewAdjustmentLayer,
    MenuPreferences,
    MenuLanguage,

    CommandOpen,
    CommandSave,
    CommandSaveAs,
    CommandExportPng,
    CommandExit,
    CommandUndo,
    CommandUndoNamed,
    CommandRedo,
    CommandRedoNamed,
    CommandSelectAll,
    CommandDeselect,
    CommandDuplicateLayer,
    CommandZoomIn,
    CommandZoomOut,
    CommandFitOnScreen,
    CommandActualPixels,
    CommandAbout,
    CommandImportImages,

    // Panels, the options bar and the status bar.
    PanelLayers,
    BlendNormal,
    BlendMultiply,
    BlendScreen,
    BlendOverlay,
    BlendDarken,
    BlendLighten,
    BlendDifference,
    BlendColorDodge,
    BlendColorBurn,
    BlendHue,
    BlendSaturation,
    BlendColor,
    BlendLuminosity,
    LabelBlendMode,
    LabelOpacity,
    LabelSize,
    LabelHardness,
    LabelStrength,
    LabelTolerance,
    LabelContiguous,
    LabelAligned,
    LabelAntiAlias,
    LabelSelectionMode,
    SelectionReplace,
    SelectionAdd,
    SelectionSubtract,
    LabelSampleSize,
    SamplePoint,
    Sample3By3,
    Sample5By5,
    LabelAllLayers,
    LabelAutoSelect,
    LabelSelectionStep,
    LabelType,
    LabelCornerRadius,
    LabelWidth,
    LabelHeight,
    LabelAngle,
    HealContentAware,
    HealCreateTexture,
    HealProximityMatch,
    GradientLinear,
    GradientRadial,
    GradientForegroundBackground,
    GradientForegroundTransparent,
    ButtonApply,
    ShapeRectangle,
    ShapeEllipse,
    TooltipForeground,
    TooltipBackground,
    TooltipSwapColors,
    TooltipDefaultColors,
    TooltipVisibility,
    TooltipNewAdjustmentLayer,
    UnitPixels,
    UnitPercent,
    StatusDocumentSize,
    StatusNoDocument,
    WelcomeTitle,
    HistoryOpacity,
    HistoryBlendMode,
    HistoryRenameLayer,
    CommandExportJpeg,
    CommandClose,
    FileTypeJpeg,
    PromptSaveChanges,

    // The Layer menu.
    LayerNameNumbered,
    LayerBackground,
    FolderNameNumbered,
    CommandNewLayer,
    CommandDeleteLayer,
    CommandMoveLayerUp,
    CommandMoveLayerDown,
    CommandGroupLayers,
    CommandMoveOutOfGroup,
    CommandShowLayer,
    CommandHideLayer,
    CommandCreateClippingMask,
    CommandReleaseClippingMask,
    CommandMergeDown,
    CommandMergeLayers,
    CommandMergeGroup,
    CommandFlipLayerHorizontal,
    CommandFlipLayerVertical,
    CommandFlipCanvasHorizontal,
    CommandFlipCanvasVertical,

    // The Select menu, pixels, the clipboard and the layer mask.
    CommandInverse,
    CommandSelectLayerPixels,
    CommandExpandSelection,
    CommandContractSelection,
    CommandInvert,
    CommandFillForeground,
    CommandFillBackground,
    CommandClear,
    CommandContentAwareFill,
    CommandLayerViaCopy,
    CommandLayerViaCut,
    CommandCut,
    CommandCopy,
    CommandCopyMerged,
    CommandPaste,
    MenuLayerMask,
    CommandAddLayerMask,
    CommandDeleteLayerMask,
    CommandDisableLayerMask,
    CommandEnableLayerMask,

    // Files and what can go wrong with them.
    DocumentUntitled,
    FileTypeProject,
    FileTypeImages,
    FileTypePng,
    ErrorCannotOpen,
    ErrorCannotSave,
    ErrorProjectInvalid,
    ErrorProjectVersion,
    ErrorProjectMissingImage,
    ErrorProjectTooLarge,
    ErrorProjectEncode,
    ErrorImageUnreadable,
    AboutText,

    // Sheets: their buttons, and the adjustments' and filters' settings.
    DialogOk,
    DialogCancel,
    DialogReset,
    LabelPreview,
    LabelRadius,
    LabelDistance,
    LabelAmount,
    NoiseUniform,
    NoiseGaussian,
    LabelMonochromatic,
    LabelRemoveDistortion,
    NoteLensDistortion,
    LabelExposure,
    LabelOffset,
    LabelGamma,
    LabelRoughness,
    LabelHue,
    LabelSaturation,
    LabelLightness,
    LabelColorize,
    NoteLimitedToSelection,
    UnitPx,
    HistoryEditAdjustmentLayer,

    // Levels.
    ChannelRgb,
    ChannelRed,
    ChannelGreen,
    ChannelBlue,
    LabelInputBlack,
    LabelInputWhite,
    LabelOutputBlack,
    LabelOutputWhite,
    LabelSample,
    SampleBlack,
    SampleGray,
    SampleWhite,
    NoteSampleBlack,
    NoteSampleGray,
    NoteSampleWhite,
    LabelAuto,
    AutoContrast,
    AutoColor,
    AutoNeutral,
    NoteHistogramOwn,
    NoteHistogramBelow,

    // Hue/Saturation's ranges, Curves, Gradient Map and the colour picker.
    RangeMaster,
    RangeReds,
    RangeYellows,
    RangeGreens,
    RangeCyans,
    RangeBlues,
    RangeMagentas,
    HueSample,
    HueAddToSample,
    HueSubtractFromSample,
    HueTargeted,
    NoteHueSample,
    NoteHueAddToSample,
    NoteHueSubtractFromSample,
    NoteHueTargeted,
    LabelInvertRange,
    NoteCurvesHelp,
    LabelCurveInput,
    LabelCurveOutput,
    CurvesRemovePoint,
    CurvesResetCurve,
    LabelShadows,
    LabelHighlights,
    LabelReverse,
    NoteColourPickerSample,
    LabelNewColour,
    LabelCurrentColour,
    LabelR,
    LabelG,
    LabelB,

    // The document's sheets — New, Canvas Size, Image Size, Export JPEG — and the options bar's transform.
    CommandNew,
    CommandCanvasSize,
    CommandImageSize,
    SheetNewCanvas,
    SheetCanvasSize,
    SheetImageSize,
    SheetExportJpeg,
    SheetWidth,
    SheetHeight,
    DialogCreate,
    DialogExport,
    UnitPixelsName,
    UnitPercentName,
    LabelRelative,
    LabelLockAspect,
    NoteCurrentSize,
    NoteNewSize,
    NoteSizeLimits,
    NoteNewCanvas,
    LabelAnchor,
    LabelCanvasExtension,
    ExtensionTransparent,
    ExtensionForeground,
    ExtensionBackground,
    ExtensionWhite,
    ExtensionBlack,
    LayerCanvasExtension,
    LabelResolution,
    UnitPixelsPerInch,
    LabelResample,
    NoteResample,
    NoteNoResample,
    LabelQuality,
    LabelMatte,
    NoteJpegSize,
    LabelScale,
    TooltipLockRatio,
    ButtonFlipHorizontal,
    ButtonFlipVertical,

    // Tabs.
    CommandNextDocument,
    CommandPreviousDocument,
    TooltipCloseTab,

    // Painting a layer mask, Smudge and Liquify, and the clone stamp over every layer.
    CommandInvertMask,
    CommandSelectMask,
    ToolSmudge,
    ToolLiquify,
    BlurModeBlur,
    LabelSampleAllLayers,
    LabelEditingMask,
    TooltipLayerMask,
    NoteMaskTool,

    // Linking a mask to its layer, moving it on its own, and copying it to another layer.
    CommandLinkMask,
    CommandUnlinkMask,
    HistoryTransformMask,
    HistoryCopyMask,
    HistoryReplaceMask,
    TooltipMaskLink,
    TooltipMaskUnlinked,

    // Remove Background, the one command that needs the AI build.
    FilterRemoveBackground,
    CommandRemoveBackgroundUnavailable,
    NoteRemoveBackground,
    NoteFindingSubject,
    NoteNoSubject,
    NoteAiUnavailable,
    NoteAiFailed,
    QualityBasic,
    QualityAdvanced,
    LabelRefine,
    LabelMatteContrast,
    LabelShiftEdge,

    // The version, and Help > Check for Updates.
    AboutVersion,
    CommandCheckUpdates,
    UpdateAvailable,
    UpdateLatest,
    UpdateFailed,
    UpdateUnreadable,

    // The Crop tool.
    ToolCrop,
    LabelAspectRatio,
    CropRatioFree,
    CropRatioOriginal,
    NoteFrameSize,
    ButtonApplyCrop,

    // Layer > Transform (Ctrl+T): floating selected pixels.
    CommandTransformSelection,
    CommandTransformLayer,
    LayerFloatingSelection,
    NoteFloating,

    // View > Pixel Grid, View > Show Transform Controls, Layer > Edit Adjustment.
    CommandPixelGrid,
    CommandTransformControls,
    CommandEditAdjustment,

    // The Layers panel: dragging rows, the row menu, the hide-all mask.
    HistoryArrangeLayers,
    CommandAddHideMask,
    CommandRenameLayer,

    // The Eyedropper, Hand and Zoom tools.
    ToolEyedropper,
    ToolHand,
    ToolZoom,

    // No tool (A), and the Eyedropper's one option.
    ToolIdle,
    LabelSampleRing,

    // The Type tool, Warp Text, the added shapes and Layer Style.
    ToolText,
    LabelFont,
    LabelBold,
    LabelItalic,
    AlignLeft,
    AlignCenter,
    AlignRight,
    LabelTracking,
    LabelLeading,
    ButtonWarp,
    TitleWarpText,
    LabelStyle,
    LabelBend,
    LabelHorizontalDistortion,
    LabelVerticalDistortion,
    WarpNone,
    WarpArc,
    WarpArcLower,
    WarpArcUpper,
    WarpArch,
    WarpBulge,
    WarpShellLower,
    WarpShellUpper,
    WarpFlag,
    WarpWave,
    WarpFish,
    WarpRise,
    WarpFisheye,
    WarpInflate,
    WarpSqueeze,
    WarpTwist,
    NoteTypeHint,
    ShapePolygon,
    ShapeStar,
    ShapeLine,
    LabelSides,
    LabelPoints,
    LabelInset,
    LabelCurved,
    LabelFill,
    LabelStroke,
    LabelLineWidth,
    HistoryAddText,
    HistoryEditText,
    HistoryTextStyle,
    CommandRasterizeType,
    CommandLayerStyle,
    HistoryLayerStyle,
    EffectShadow,
    EffectGlow,
    EffectStroke,
    LabelSpread,
    LabelPosition,
    StrokeOutside,
    StrokeInside,
    StrokeCenter,
    LabelColour,
    LabelBlendMode,
}

/// <summary>
/// The words, each phrase in both languages on one line.
/// </summary>
/// <remarks>
/// <para>
/// The Korean follows the Korean edition of Photoshop wherever it has a word for the thing —
/// 혼합 모드, 그레이디언트, 자동 선택 도구, 스팟 복구 브러시 — since that is the vocabulary the
/// people this is for already know (docs/windows-port.md §6).
/// </para>
/// <para>
/// This file is the only one in the source tree allowed to hold Korean, and a test holds it to
/// that: a Korean phrase anywhere else is a phrase the English interface would show untranslated.
/// </para>
/// </remarks>
public static class TextTable
{
    public static readonly (TextKey Key, string English, string Korean)[] Entries =
    [
        (TextKey.AppTitle, "Compositor", "Compositor 한국어판"),

        (TextKey.LanguageEnglish, "English", "English"),
        (TextKey.LanguageKorean, "한국어", "한국어"),

        (TextKey.ToolMove, "Move Tool", "이동 도구"),
        (TextKey.ToolRectangleMarquee, "Rectangular Marquee Tool", "사각형 선택 윤곽 도구"),
        (TextKey.ToolEllipseMarquee, "Elliptical Marquee Tool", "원형 선택 윤곽 도구"),
        (TextKey.ToolLasso, "Lasso Tool", "올가미 도구"),
        (TextKey.ToolPolygonLasso, "Polygonal Lasso Tool", "다각형 올가미 도구"),
        (TextKey.ToolBrush, "Brush Tool", "브러시 도구"),
        (TextKey.ToolEraser, "Eraser Tool", "지우개 도구"),
        (TextKey.ToolCloneStamp, "Clone Stamp Tool", "복제 도장 도구"),
        (TextKey.ToolBlur, "Blur Tool", "흐림 효과 도구"),
        (TextKey.ToolHeal, "Spot Healing Brush Tool", "스팟 복구 브러시 도구"),
        (TextKey.ToolMagicWand, "Magic Wand Tool", "자동 선택 도구"),
        (TextKey.ToolGradient, "Gradient Tool", "그레이디언트 도구"),
        (TextKey.ToolShape, "Shape Tool", "모양 도구"),

        (TextKey.AdjustLevels, "Levels", "레벨"),
        (TextKey.AdjustCurves, "Curves", "곡선"),
        (TextKey.AdjustHueSaturation, "Hue/Saturation", "색조/채도"),
        (TextKey.AdjustExposure, "Exposure", "노출"),
        (TextKey.AdjustGradientMap, "Gradient Map", "그레이디언트 맵"),
        (TextKey.AdjustGrain, "Grain", "그레인"),

        (TextKey.FilterGaussianBlur, "Gaussian Blur", "가우시안 흐림 효과"),
        (TextKey.FilterMotionBlur, "Motion Blur", "동작 흐림 효과"),
        (TextKey.FilterAddNoise, "Add Noise", "노이즈 추가"),
        (TextKey.FilterLensCorrection, "Lens Correction", "렌즈 교정"),

        (TextKey.HistoryEdit, "Edit", "편집"),
        (TextKey.HistoryDuplicateLayer, "Duplicate Layer", "레이어 복제"),
        (TextKey.HistoryMoveLayer, "Move", "이동"),
        (TextKey.HistoryTransformLayer, "Transform", "변형"),
        (TextKey.HistoryMoveSelection, "Move Selection", "선택 영역 이동"),
        (TextKey.HistoryDuplicateSelection, "Duplicate Selection", "선택 영역 복제"),
        (TextKey.HistoryAdjustmentLayer, "New {0} Layer", "새 {0} 레이어"),
        (TextKey.LayerCopyName, "{0} copy", "{0} 복사"),

        (TextKey.MenuFile, "&File", "파일(&F)"),
        (TextKey.MenuEdit, "&Edit", "편집(&E)"),
        (TextKey.MenuImage, "&Image", "이미지(&I)"),
        (TextKey.MenuLayer, "&Layer", "레이어(&L)"),
        (TextKey.MenuSelect, "&Select", "선택(&S)"),
        (TextKey.MenuFilter, "Fil&ter", "필터(&T)"),
        (TextKey.MenuView, "&View", "보기(&V)"),
        (TextKey.MenuHelp, "&Help", "도움말(&H)"),
        (TextKey.MenuAdjustments, "&Adjustments", "조정(&J)"),
        (TextKey.MenuNewAdjustmentLayer, "New Ad&justment Layer", "새 조정 레이어(&J)"),
        (TextKey.MenuPreferences, "Pre&ferences", "환경 설정(&N)"),
        (TextKey.MenuLanguage, "&Language", "언어(&L)"),

        (TextKey.CommandOpen, "&Open…", "열기(&O)…"),
        (TextKey.CommandSave, "&Save", "저장(&S)"),
        (TextKey.CommandSaveAs, "Save &As…", "다른 이름으로 저장(&A)…"),
        (TextKey.CommandExportPng, "Export as &PNG…", "PNG로 내보내기(&P)…"),
        (TextKey.CommandExit, "E&xit", "끝내기(&X)"),
        (TextKey.CommandUndo, "&Undo", "실행 취소(&U)"),
        (TextKey.CommandUndoNamed, "&Undo {0}", "{0} 실행 취소(&U)"),
        (TextKey.CommandRedo, "&Redo", "다시 실행(&R)"),
        (TextKey.CommandRedoNamed, "&Redo {0}", "{0} 다시 실행(&R)"),
        (TextKey.CommandSelectAll, "&All", "모두(&A)"),
        (TextKey.CommandDeselect, "&Deselect", "선택 해제(&D)"),
        (TextKey.CommandDuplicateLayer, "&Duplicate Layer", "레이어 복제(&D)"),
        (TextKey.CommandZoomIn, "Zoom &In", "확대(&I)"),
        (TextKey.CommandZoomOut, "Zoom &Out", "축소(&O)"),
        (TextKey.CommandFitOnScreen, "&Fit on Screen", "화면 크기에 맞추기(&F)"),
        (TextKey.CommandActualPixels, "&Actual Pixels", "실제 픽셀(&A)"),
        (TextKey.CommandAbout, "&About Compositor", "Compositor 정보(&A)"),
        (TextKey.PanelLayers, "Layers", "레이어"),
        (TextKey.BlendNormal, "Normal", "표준"),
        (TextKey.BlendMultiply, "Multiply", "곱하기"),
        (TextKey.BlendScreen, "Screen", "스크린"),
        (TextKey.BlendOverlay, "Overlay", "오버레이"),
        (TextKey.BlendDarken, "Darken", "어둡게 하기"),
        (TextKey.BlendLighten, "Lighten", "밝게 하기"),
        (TextKey.BlendDifference, "Difference", "차이"),
        (TextKey.BlendColorDodge, "Color Dodge", "색상 닷지"),
        (TextKey.BlendColorBurn, "Color Burn", "색상 번"),
        (TextKey.BlendHue, "Hue", "색조"),
        (TextKey.BlendSaturation, "Saturation", "채도"),
        (TextKey.BlendColor, "Color", "색상"),
        (TextKey.BlendLuminosity, "Luminosity", "광도"),
        (TextKey.LabelBlendMode, "Blend Mode", "혼합 모드"),
        (TextKey.LabelOpacity, "Opacity", "불투명도"),
        (TextKey.LabelSize, "Size", "크기"),
        (TextKey.LabelHardness, "Hardness", "경도"),
        (TextKey.LabelStrength, "Strength", "강도"),
        (TextKey.LabelTolerance, "Tolerance", "허용치"),
        (TextKey.LabelContiguous, "Contiguous", "인접"),
        (TextKey.LabelAligned, "Aligned", "정렬"),
        (TextKey.LabelAntiAlias, "Anti-alias", "앤티 앨리어스"),
        (TextKey.LabelSelectionStep, "Expand/Contract", "확장/축소"),
        (TextKey.LabelType, "Type", "유형"),
        (TextKey.LabelCornerRadius, "Corner Radius", "모퉁이 반경"),
        (TextKey.LabelWidth, "W", "너비"),
        (TextKey.LabelHeight, "H", "높이"),
        (TextKey.LabelAngle, "Angle", "각도"),
        (TextKey.HealContentAware, "Content-Aware", "내용 인식"),
        (TextKey.HealCreateTexture, "Create Texture", "텍스처 만들기"),
        (TextKey.HealProximityMatch, "Proximity Match", "근접 일치"),
        (TextKey.GradientLinear, "Linear", "선형"),
        (TextKey.GradientRadial, "Radial", "방사형"),
        (TextKey.GradientForegroundBackground, "Foreground to Background", "전경색에서 배경색"),
        (TextKey.GradientForegroundTransparent, "Foreground to Transparent", "전경색에서 투명"),
        (TextKey.ButtonApply, "Apply", "적용"),
        (TextKey.ShapeRectangle, "Rectangle", "사각형"),
        (TextKey.ShapeEllipse, "Ellipse", "타원"),
        (TextKey.TooltipForeground, "Foreground Color", "전경색"),
        (TextKey.TooltipBackground, "Background Color", "배경색"),
        (TextKey.TooltipSwapColors, "Swap Colors (X)", "색상 바꾸기 (X)"),
        (TextKey.TooltipDefaultColors, "Default Colors (D)", "기본 색상 (D)"),
        (TextKey.TooltipVisibility, "Show or Hide", "표시/숨기기"),
        (TextKey.TooltipNewAdjustmentLayer, "New Adjustment Layer", "새 조정 레이어"),
        (TextKey.UnitPixels, "{0} px", "{0}픽셀"),
        (TextKey.UnitPercent, "{0}%", "{0}%"),
        (TextKey.StatusDocumentSize, "{0} × {1} px", "{0} × {1}픽셀"),
        (TextKey.StatusNoDocument, "No document", "문서 없음"),
        (TextKey.WelcomeTitle, "Open an image or a project to begin.", "이미지나 프로젝트를 열어 시작하세요."),
        (TextKey.HistoryOpacity, "Opacity", "불투명도"),
        (TextKey.HistoryBlendMode, "Blend Mode", "혼합 모드"),
        (TextKey.HistoryRenameLayer, "Rename Layer", "레이어 이름 바꾸기"),
        (TextKey.CommandImportImages, "&Import Images…", "이미지 가져오기(&I)…"),
        (TextKey.CommandExportJpeg, "Export as &JPEG…", "JPEG로 내보내기(&J)…"),
        (TextKey.CommandClose, "&Close", "닫기(&C)"),
        (TextKey.FileTypeJpeg, "JPEG image", "JPEG 이미지"),
        (TextKey.PromptSaveChanges, "Save the changes to {0} before closing it?",
                                    "{0}을(를) 닫기 전에 변경 사항을 저장하시겠습니까?"),

        (TextKey.LayerNameNumbered, "Layer {0}", "레이어 {0}"),
        (TextKey.LayerBackground, "Background", "배경"),
        (TextKey.FolderNameNumbered, "Group {0}", "그룹 {0}"),
        (TextKey.CommandNewLayer, "&New Layer", "새 레이어(&N)"),
        (TextKey.CommandDeleteLayer, "De&lete Layer", "레이어 삭제(&L)"),
        (TextKey.CommandMoveLayerUp, "Bring For&ward", "앞으로 가져오기(&W)"),
        (TextKey.CommandMoveLayerDown, "Send Bac&kward", "뒤로 보내기(&K)"),
        (TextKey.CommandGroupLayers, "&Group Layers", "레이어 그룹화(&G)"),
        (TextKey.CommandMoveOutOfGroup, "Move &Out of Group", "그룹에서 꺼내기(&O)"),
        (TextKey.CommandShowLayer, "&Show Layer", "레이어 표시(&S)"),
        (TextKey.CommandHideLayer, "&Hide Layer", "레이어 숨기기(&H)"),
        (TextKey.CommandCreateClippingMask, "Create &Clipping Mask", "클리핑 마스크 만들기(&C)"),
        (TextKey.CommandReleaseClippingMask, "Release &Clipping Mask", "클리핑 마스크 해제(&C)"),
        (TextKey.CommandMergeDown, "&Merge Down", "아래로 병합(&E)"),
        (TextKey.CommandMergeLayers, "&Merge Layers", "레이어 병합(&E)"),
        (TextKey.CommandMergeGroup, "&Merge Group", "그룹 병합(&E)"),
        (TextKey.CommandFlipLayerHorizontal, "Flip Layer &Horizontal", "레이어 가로로 뒤집기(&H)"),
        (TextKey.CommandFlipLayerVertical, "Flip Layer &Vertical", "레이어 세로로 뒤집기(&V)"),
        (TextKey.CommandFlipCanvasHorizontal, "Flip Canvas &Horizontal", "캔버스 가로로 뒤집기(&H)"),
        (TextKey.CommandFlipCanvasVertical, "Flip Canvas &Vertical", "캔버스 세로로 뒤집기(&V)"),

        (TextKey.CommandInverse, "&Inverse", "반전(&I)"),
        (TextKey.CommandSelectLayerPixels, "&Layer Pixels", "레이어 픽셀(&L)"),
        (TextKey.CommandExpandSelection, "&Expand by {0} px", "{0}픽셀 확장(&E)"),
        (TextKey.CommandContractSelection, "&Contract by {0} px", "{0}픽셀 축소(&C)"),
        (TextKey.CommandInvert, "In&vert", "색상 반전(&V)"),
        (TextKey.CommandFillForeground, "Fill with &Foreground Color", "전경색으로 칠하기(&F)"),
        (TextKey.CommandFillBackground, "Fill with &Background Color", "배경색으로 칠하기(&B)"),
        (TextKey.CommandClear, "Cl&ear", "지우기(&E)"),
        (TextKey.CommandContentAwareFill, "Content-A&ware Fill", "내용 인식 채우기(&W)"),
        (TextKey.CommandLayerViaCopy, "Layer via &Copy", "복사한 레이어(&C)"),
        (TextKey.CommandLayerViaCut, "Layer via Cu&t", "잘라낸 레이어(&T)"),
        (TextKey.CommandCut, "Cu&t", "잘라내기(&T)"),
        (TextKey.CommandCopy, "&Copy", "복사(&C)"),
        (TextKey.CommandCopyMerged, "Copy Mer&ged", "병합하여 복사(&Y)"),
        (TextKey.CommandPaste, "&Paste", "붙여넣기(&P)"),
        (TextKey.MenuLayerMask, "Layer &Mask", "레이어 마스크(&M)"),
        (TextKey.CommandAddLayerMask, "&Add Layer Mask", "레이어 마스크 추가(&A)"),
        (TextKey.CommandDeleteLayerMask, "&Delete Layer Mask", "레이어 마스크 삭제(&D)"),
        (TextKey.CommandDisableLayerMask, "Disa&ble Layer Mask", "레이어 마스크 사용 안 함(&B)"),
        (TextKey.CommandEnableLayerMask, "Ena&ble Layer Mask", "레이어 마스크 사용(&B)"),

        (TextKey.DocumentUntitled, "Untitled", "제목 없음"),
        (TextKey.FileTypeProject, "Compositor project", "Compositor 프로젝트"),
        (TextKey.FileTypeImages, "Images", "이미지"),
        (TextKey.FileTypePng, "PNG image", "PNG 이미지"),
        (TextKey.ErrorCannotOpen, "{0} could not be opened.", "{0}을(를) 열 수 없습니다."),
        (TextKey.ErrorCannotSave, "{0} could not be saved.", "{0}을(를) 저장할 수 없습니다."),
        (TextKey.ErrorProjectInvalid, "It is not a Compositor project, or it is damaged.",
                                      "Compositor 프로젝트가 아니거나 손상되었습니다."),
        (TextKey.ErrorProjectVersion, "It was saved in a newer format ({0}) than this version reads.",
                                      "이 버전이 읽지 못하는 새 형식({0})으로 저장된 프로젝트입니다."),
        (TextKey.ErrorProjectMissingImage, "An image it refers to is missing.",
                                           "프로젝트가 가리키는 이미지가 없습니다."),
        (TextKey.ErrorProjectTooLarge, "It is larger than a project may be.",
                                       "프로젝트가 허용되는 크기를 넘습니다."),
        (TextKey.ErrorProjectEncode, "Its pixels could not be written.", "픽셀을 기록하지 못했습니다."),
        (TextKey.ErrorImageUnreadable, "The image could not be read.", "이미지를 읽을 수 없습니다."),
        (TextKey.AboutText,
            "Compositor for Windows\n\nA reimplementation of Compositor by Wonder Assembly LLC, "
            + "used under the MIT License.",
            "Compositor 윈도우판\n\nWonder Assembly LLC의 Compositor를 MIT 라이선스에 따라 "
            + "다시 구현한 프로그램입니다."),
        (TextKey.DialogOk, "OK", "확인"),
        (TextKey.DialogCancel, "Cancel", "취소"),
        (TextKey.DialogReset, "Reset", "재설정"),
        (TextKey.LabelPreview, "Preview", "미리 보기"),
        (TextKey.LabelRadius, "Radius", "반경"),
        (TextKey.LabelDistance, "Distance", "거리"),
        (TextKey.LabelAmount, "Amount", "양"),
        (TextKey.NoiseUniform, "Uniform", "균일"),
        (TextKey.NoiseGaussian, "Gaussian", "가우시안"),
        (TextKey.LabelMonochromatic, "Monochromatic", "단색"),
        (TextKey.LabelRemoveDistortion, "Remove Distortion", "왜곡 제거"),
        (TextKey.NoteLensDistortion, "Positive straightens lines that bow outward (barrel); negative, lines that bow inward (pincushion).", "양수는 바깥으로 휜 선(술통형)을, 음수는 안쪽으로 휜 선(실패형)을 곧게 폅니다."),
        (TextKey.LabelExposure, "Exposure", "노출"),
        (TextKey.LabelOffset, "Offset", "오프셋"),
        (TextKey.LabelGamma, "Gamma", "감마"),
        (TextKey.LabelRoughness, "Roughness", "거칠기"),
        (TextKey.LabelHue, "Hue", "색조"),
        (TextKey.LabelSaturation, "Saturation", "채도"),
        (TextKey.LabelLightness, "Lightness", "밝기"),
        (TextKey.LabelColorize, "Colorize", "색상화"),
        (TextKey.NoteLimitedToSelection, "Limited to the selection", "선택 영역에만 적용됩니다"),
        (TextKey.UnitPx, "px", "픽셀"),
        (TextKey.HistoryEditAdjustmentLayer, "Edit {0} Layer", "{0} 레이어 편집"),
        (TextKey.ChannelRgb, "RGB", "RGB"),
        (TextKey.ChannelRed, "Red", "빨강"),
        (TextKey.ChannelGreen, "Green", "녹색"),
        (TextKey.ChannelBlue, "Blue", "파랑"),
        (TextKey.LabelInputBlack, "Input Black", "입력 검정"),
        (TextKey.LabelInputWhite, "Input White", "입력 흰색"),
        (TextKey.LabelOutputBlack, "Output Black", "출력 검정"),
        (TextKey.LabelOutputWhite, "Output White", "출력 흰색"),
        (TextKey.LabelSample, "Sample", "샘플"),
        (TextKey.SampleBlack, "Black", "검정"),
        (TextKey.SampleGray, "Gray", "회색"),
        (TextKey.SampleWhite, "White", "흰색"),
        (TextKey.NoteSampleBlack, "Click the image to set the black point. Click the eyedropper again to stop.", "이미지를 클릭해 검정 기준점을 정하세요. 스포이드를 다시 누르면 멈춥니다."),
        (TextKey.NoteSampleGray, "Click the image to set the gray point. Click the eyedropper again to stop.", "이미지를 클릭해 회색 기준점을 정하세요. 스포이드를 다시 누르면 멈춥니다."),
        (TextKey.NoteSampleWhite, "Click the image to set the white point. Click the eyedropper again to stop.", "이미지를 클릭해 흰색 기준점을 정하세요. 스포이드를 다시 누르면 멈춥니다."),
        (TextKey.LabelAuto, "Auto", "자동"),
        (TextKey.AutoContrast, "Contrast", "대비"),
        (TextKey.AutoColor, "Color", "색상"),
        (TextKey.AutoNeutral, "Color + Neutral Midtones", "색상 + 중간톤 중립"),
        (TextKey.NoteHistogramOwn, "Histogram of the layer's own pixels, weighted by their opacity.", "레이어 자체 픽셀의 히스토그램입니다(불투명도로 가중)."),
        (TextKey.NoteHistogramBelow, "Histogram of the layers below, which is what this adjustment layer changes.", "이 조정 레이어가 바꾸는 아래 레이어들의 히스토그램입니다."),
        (TextKey.RangeMaster, "Master", "마스터"),
        (TextKey.RangeReds, "Reds", "빨강 계열"),
        (TextKey.RangeYellows, "Yellows", "노랑 계열"),
        (TextKey.RangeGreens, "Greens", "녹색 계열"),
        (TextKey.RangeCyans, "Cyans", "녹청 계열"),
        (TextKey.RangeBlues, "Blues", "파랑 계열"),
        (TextKey.RangeMagentas, "Magentas", "마젠타 계열"),
        (TextKey.HueSample, "Sample", "샘플"),
        (TextKey.HueAddToSample, "Add to Sample", "샘플에 추가"),
        (TextKey.HueSubtractFromSample, "Subtract from Sample", "샘플에서 빼기"),
        (TextKey.HueTargeted, "Targeted Adjustment", "대상 조정"),
        (TextKey.NoteHueSample, "Click the image to center this range on that color.", "이미지를 클릭하면 이 범위를 그 색의 가운데로 옮깁니다."),
        (TextKey.NoteHueAddToSample, "Click the image to widen this range to include that color.", "이미지를 클릭하면 그 색이 들어오도록 이 범위를 넓힙니다."),
        (TextKey.NoteHueSubtractFromSample, "Click the image to narrow this range to exclude that color.", "이미지를 클릭하면 그 색이 빠지도록 이 범위를 좁힙니다."),
        (TextKey.NoteHueTargeted, "Drag on the image to change that color's saturation; hold Ctrl to change its hue.", "이미지 위를 끌면 그 색의 채도가 바뀝니다. Ctrl을 누르고 끌면 색조가 바뀝니다."),
        (TextKey.LabelInvertRange, "Apply outside this range instead", "이 범위 밖에 대신 적용"),
        (TextKey.NoteCurvesHelp, "Click to add a point. Drag to adjust.", "클릭해 점을 추가하고, 끌어서 조정하세요."),
        (TextKey.LabelCurveInput, "Input", "입력"),
        (TextKey.LabelCurveOutput, "Output", "출력"),
        (TextKey.CurvesRemovePoint, "Remove Point", "점 삭제"),
        (TextKey.CurvesResetCurve, "Reset Curve", "곡선 재설정"),
        (TextKey.LabelShadows, "Shadows", "어두운 영역"),
        (TextKey.LabelHighlights, "Highlights", "밝은 영역"),
        (TextKey.LabelReverse, "Reverse", "반전"),
        (TextKey.NoteColourPickerSample, "Click the canvas to sample a color.", "캔버스를 클릭하면 색을 추출합니다."),
        (TextKey.LabelNewColour, "New", "새 색상"),
        (TextKey.LabelCurrentColour, "Current", "현재 색상"),
        (TextKey.LabelR, "R", "R"),
        (TextKey.LabelG, "G", "G"),
        (TextKey.LabelB, "B", "B"),
        (TextKey.CommandNew, "&New…", "새로 만들기(&N)…"),
        (TextKey.CommandCanvasSize, "Canvas Si&ze…", "캔버스 크기(&Z)…"),
        (TextKey.CommandImageSize, "Image &Size…", "이미지 크기(&S)…"),
        (TextKey.SheetNewCanvas, "New Canvas", "새 캔버스"),
        (TextKey.SheetCanvasSize, "Canvas Size", "캔버스 크기"),
        (TextKey.SheetImageSize, "Image Size", "이미지 크기"),
        (TextKey.SheetExportJpeg, "Export JPEG", "JPEG로 내보내기"),
        (TextKey.SheetWidth, "Width", "너비"),
        (TextKey.SheetHeight, "Height", "높이"),
        (TextKey.DialogCreate, "Create", "만들기"),
        (TextKey.DialogExport, "Export…", "내보내기…"),
        (TextKey.UnitPixelsName, "Pixels", "픽셀"),
        (TextKey.UnitPercentName, "Percent", "퍼센트"),
        (TextKey.LabelRelative, "Relative", "상대치"),
        (TextKey.LabelLockAspect, "Lock aspect ratio", "가로세로 비율 고정"),
        (TextKey.NoteCurrentSize, "Current size: {0} × {1} px", "현재 크기: {0} × {1}픽셀"),
        (TextKey.NoteNewSize, "New size: {0} × {1} px", "새 크기: {0} × {1}픽셀"),
        (TextKey.NoteSizeLimits, "Use 1 to 30,000 pixels a side, and no more than 100 megapixels in all.", "한 변은 1–30,000픽셀, 전체는 1억 픽셀 이하로 정하세요."),
        (TextKey.NoteNewCanvas, "A transparent canvas, in sRGB.", "투명한 sRGB 캔버스입니다."),
        (TextKey.LabelAnchor, "Anchor", "기준점"),
        (TextKey.LabelCanvasExtension, "Extension color", "확장 색상"),
        (TextKey.ExtensionTransparent, "Transparent", "투명"),
        (TextKey.ExtensionForeground, "Foreground", "전경색"),
        (TextKey.ExtensionBackground, "Background", "배경색"),
        (TextKey.ExtensionWhite, "White", "흰색"),
        (TextKey.ExtensionBlack, "Black", "검정"),
        (TextKey.LayerCanvasExtension, "Canvas Extension", "캔버스 확장"),
        (TextKey.LabelResolution, "Resolution", "해상도"),
        (TextKey.UnitPixelsPerInch, "px/in", "픽셀/인치"),
        (TextKey.LabelResample, "Resample", "리샘플링"),
        (TextKey.NoteResample, "Resamples every layer's pixels. Undo brings the originals back.", "모든 레이어의 픽셀을 다시 샘플링합니다. 실행 취소하면 원래대로 돌아옵니다."),
        (TextKey.NoteNoResample, "Only the resolution changes; the pixels stay as they are.", "해상도만 바뀌고 픽셀은 그대로입니다."),
        (TextKey.LabelQuality, "Quality", "품질"),
        (TextKey.LabelMatte, "Background for transparency", "투명 영역의 배경색"),
        (TextKey.NoteJpegSize, "{0} × {1} px · {2}", "{0} × {1}픽셀 · {2}"),
        (TextKey.LabelScale, "Scale", "비율"),
        (TextKey.TooltipLockRatio, "Keep proportions", "비율 유지"),
        (TextKey.ButtonFlipHorizontal, "Flip H", "가로 뒤집기"),
        (TextKey.ButtonFlipVertical, "Flip V", "세로 뒤집기"),
        (TextKey.CommandNextDocument, "&Next Document", "다음 문서(&N)"),
        (TextKey.CommandPreviousDocument, "&Previous Document", "이전 문서(&P)"),
        (TextKey.TooltipCloseTab, "Close", "닫기"),
        (TextKey.CommandInvertMask, "In&vert Mask", "마스크 반전(&V)"),
        (TextKey.CommandSelectMask, "&Mask's Black Areas", "마스크의 검은 영역(&M)"),
        (TextKey.ToolSmudge, "Smudge", "문지르기"),
        (TextKey.ToolLiquify, "Liquify", "픽셀 유동화"),
        (TextKey.BlurModeBlur, "Blur", "흐리게"),
        (TextKey.LabelSampleAllLayers, "Sample all layers", "모든 레이어 샘플링"),
        (TextKey.LabelEditingMask, "Mask", "마스크"),
        (TextKey.TooltipLayerMask, "Layer mask — click to paint it", "레이어 마스크 — 클릭하면 마스크에 칠합니다"),
        (TextKey.NoteMaskTool, "This tool works on pixels, not on a mask.", "이 도구는 마스크가 아닌 픽셀에만 작동합니다."),
        (TextKey.CommandLinkMask, "&Link Layer Mask", "레이어 마스크 연결(&L)"),
        (TextKey.CommandUnlinkMask, "Un&link Layer Mask", "레이어 마스크 연결 해제(&L)"),
        (TextKey.HistoryTransformMask, "Transform Layer Mask", "레이어 마스크 변형"),
        (TextKey.HistoryCopyMask, "Copy Layer Mask", "레이어 마스크 복사"),
        (TextKey.HistoryReplaceMask, "Replace Layer Mask", "레이어 마스크 교체"),
        (TextKey.TooltipMaskLink, "Link the layer and its mask so they move together", "레이어와 마스크를 연결해 함께 움직입니다"),
        (TextKey.TooltipMaskUnlinked, "Unlinked: the mask moves on its own. Click to link", "연결 해제됨: 마스크가 따로 움직입니다. 클릭하면 연결합니다"),
        (TextKey.FilterRemoveBackground, "Remove Background", "배경 제거"),
        (TextKey.CommandRemoveBackgroundUnavailable, "Remove Background (AI build only)", "배경 제거 (AI 포함판 전용)"),
        (TextKey.NoteRemoveBackground, "Hide the background behind a layer mask, keeping the foreground subjects. The pixels stay, so the background can be painted back at any time.", "전경의 피사체는 남기고 배경을 레이어 마스크로 가립니다. 픽셀은 그대로 남으므로 언제든 배경을 다시 칠해 되살릴 수 있습니다."),
        (TextKey.NoteFindingSubject, "Finding the subject…", "피사체를 찾는 중…"),
        (TextKey.NoteNoSubject, "No subject was found in this layer. Try an image with a more distinct subject.", "이 레이어에서 피사체를 찾지 못했습니다. 피사체가 더 뚜렷한 이미지로 시도해 보세요."),
        (TextKey.NoteAiUnavailable, "Remove Background needs the AI build of Compositor.", "배경 제거는 AI 포함판에서 쓸 수 있습니다."),
        (TextKey.NoteAiFailed, "The model could not run: {0}", "모델을 실행하지 못했습니다: {0}"),
        (TextKey.QualityBasic, "Basic", "기본"),
        (TextKey.QualityAdvanced, "Advanced", "고급"),
        (TextKey.LabelRefine, "Refine", "다듬기"),
        (TextKey.LabelMatteContrast, "Contrast", "대비"),
        (TextKey.LabelShiftEdge, "Shift Edge", "가장자리 이동"),
        (TextKey.AboutVersion, "Version {0}", "버전 {0}"),
        (TextKey.CommandCheckUpdates, "Check for &Updates…", "업데이트 확인(&U)…"),
        (TextKey.UpdateAvailable, "Version {0} is available (you have {1}). Open the download page?", "새 버전 {0}이(가) 나왔습니다(현재 {1}). 다운로드 페이지를 열까요?"),
        (TextKey.UpdateLatest, "You have the latest version ({0}).", "최신 버전입니다({0})."),
        (TextKey.UpdateFailed, "Could not check for updates: {0}", "업데이트를 확인하지 못했습니다: {0}"),
        (TextKey.UpdateUnreadable, "the update feed could not be read", "업데이트 정보를 읽을 수 없습니다"),
        (TextKey.ToolCrop, "Crop Tool", "자르기 도구"),
        (TextKey.LabelAspectRatio, "Ratio", "가로세로 비율"),
        (TextKey.CropRatioFree, "Free", "자유"),
        (TextKey.CropRatioOriginal, "Original", "원본 비율"),
        (TextKey.NoteFrameSize, "{0} × {1} px", "{0} × {1}픽셀"),
        (TextKey.ButtonApplyCrop, "Apply Crop", "자르기 적용"),
        (TextKey.CommandTransformSelection, "&Transform Selection", "선택 영역 변형(&T)"),
        (TextKey.CommandTransformLayer, "&Transform Layer", "레이어 변형(&T)"),
        (TextKey.LayerFloatingSelection, "Floating Selection", "떠 있는 선택 영역"),
        (TextKey.NoteFloating, "Enter applies, Esc cancels", "Enter로 적용, Esc로 취소"),
        (TextKey.CommandPixelGrid, "&Pixel Grid (800% and above)", "픽셀 격자(800% 이상)(&P)"),
        (TextKey.CommandTransformControls, "Show &Transform Controls", "변형 컨트롤 표시(&T)"),
        (TextKey.CommandEditAdjustment, "&Edit Adjustment", "조정 편집(&E)"),
        (TextKey.HistoryArrangeLayers, "Arrange Layers", "레이어 순서 변경"),
        (TextKey.CommandAddHideMask, "Add &Hide-All Mask", "모두 가리는 마스크 추가(&H)"),
        (TextKey.CommandRenameLayer, "Rename…", "이름 바꾸기…"),
        (TextKey.ToolEyedropper, "Eyedropper Tool", "스포이드 도구"),
        (TextKey.ToolHand, "Hand Tool", "손 도구"),
        (TextKey.ToolZoom, "Zoom Tool", "돋보기 도구"),
        (TextKey.LabelSelectionMode, "Selection", "선택"),
        (TextKey.SelectionReplace, "New", "새 선택"),
        (TextKey.SelectionAdd, "Add", "추가"),
        (TextKey.SelectionSubtract, "Subtract", "빼기"),
        (TextKey.LabelSampleSize, "Sample Size", "표본 크기"),
        (TextKey.SamplePoint, "Point", "포인트"),
        (TextKey.Sample3By3, "3 × 3", "3 × 3"),
        (TextKey.Sample5By5, "5 × 5", "5 × 5"),
        (TextKey.LabelAllLayers, "All Layers", "모든 레이어"),
        (TextKey.LabelAutoSelect, "Auto Select", "자동 선택"),
        (TextKey.ToolIdle, "Select a tool", "도구를 선택하세요"),
        (TextKey.LabelSampleRing, "Sample Ring", "샘플 링"),
        (TextKey.ToolText, "Type Tool", "문자 도구"),
        (TextKey.LabelFont, "Font", "글꼴"),
        (TextKey.LabelBold, "Bold", "굵게"),
        (TextKey.LabelItalic, "Italic", "기울임"),
        (TextKey.AlignLeft, "Left", "왼쪽"),
        (TextKey.AlignCenter, "Center", "가운데"),
        (TextKey.AlignRight, "Right", "오른쪽"),
        (TextKey.LabelTracking, "Tracking", "자간"),
        (TextKey.LabelLeading, "Leading", "행간"),
        (TextKey.ButtonWarp, "Warp…", "뒤틀기…"),
        (TextKey.TitleWarpText, "Warp Text", "텍스트 뒤틀기"),
        (TextKey.LabelStyle, "Style", "스타일"),
        (TextKey.LabelBend, "Bend", "구부리기"),
        (TextKey.LabelHorizontalDistortion, "Horizontal Distortion", "가로 왜곡"),
        (TextKey.LabelVerticalDistortion, "Vertical Distortion", "세로 왜곡"),
        (TextKey.WarpNone, "None", "없음"),
        (TextKey.WarpArc, "Arc", "부채꼴"),
        (TextKey.WarpArcLower, "Arc Lower", "아래 부채꼴"),
        (TextKey.WarpArcUpper, "Arc Upper", "위 부채꼴"),
        (TextKey.WarpArch, "Arch", "아치"),
        (TextKey.WarpBulge, "Bulge", "돌출"),
        (TextKey.WarpShellLower, "Shell Lower", "아래가 넓은 조개"),
        (TextKey.WarpShellUpper, "Shell Upper", "위가 넓은 조개"),
        (TextKey.WarpFlag, "Flag", "깃발"),
        (TextKey.WarpWave, "Wave", "파형"),
        (TextKey.WarpFish, "Fish", "물고기"),
        (TextKey.WarpRise, "Rise", "상승"),
        (TextKey.WarpFisheye, "Fisheye", "물고기 눈"),
        (TextKey.WarpInflate, "Inflate", "부풀리기"),
        (TextKey.WarpSqueeze, "Squeeze", "양쪽 누르기"),
        (TextKey.WarpTwist, "Twist", "비틀기"),
        (TextKey.NoteTypeHint, "Click the canvas to add text, or click text to edit it", "캔버스를 클릭하면 글자를 넣고, 글자를 클릭하면 고칩니다"),
        (TextKey.ShapePolygon, "Polygon", "다각형"),
        (TextKey.ShapeStar, "Star", "별"),
        (TextKey.ShapeLine, "Line", "선"),
        (TextKey.LabelSides, "Sides", "변"),
        (TextKey.LabelPoints, "Points", "꼭짓점"),
        (TextKey.LabelInset, "Inset", "안쪽 깊이"),
        (TextKey.LabelCurved, "Curved", "곡선"),
        (TextKey.LabelFill, "Fill", "칠"),
        (TextKey.LabelStroke, "Stroke", "획"),
        (TextKey.LabelLineWidth, "Weight", "두께"),
        (TextKey.HistoryAddText, "Add Text", "텍스트 추가"),
        (TextKey.HistoryEditText, "Edit Text", "텍스트 편집"),
        (TextKey.HistoryTextStyle, "Text Style", "텍스트 스타일"),
        (TextKey.CommandRasterizeType, "Rasteri&ze Type", "문자 래스터화(&Z)"),
        (TextKey.CommandLayerStyle, "Layer St&yle", "레이어 스타일(&Y)"),
        (TextKey.HistoryLayerStyle, "Layer Style", "레이어 스타일"),
        (TextKey.EffectShadow, "Drop Shadow", "드롭 섀도"),
        (TextKey.EffectGlow, "Outer Glow", "외부 광선"),
        (TextKey.EffectStroke, "Stroke", "획"),
        (TextKey.LabelSpread, "Spread", "스프레드"),
        (TextKey.LabelPosition, "Position", "위치"),
        (TextKey.StrokeOutside, "Outside", "바깥쪽"),
        (TextKey.StrokeInside, "Inside", "안쪽"),
        (TextKey.StrokeCenter, "Center", "가운데"),
        (TextKey.LabelColour, "Color", "색상"),
        (TextKey.LabelBlendMode, "Blend Mode", "혼합 모드"),
    ];

    /// <summary>Phrases that are the same in both languages on purpose — names, not words.</summary>
    public static readonly FrozenSet<TextKey> Untranslated =
        new[]
        {
            TextKey.LanguageEnglish, TextKey.LanguageKorean, TextKey.UnitPercent, TextKey.ChannelRgb,
            TextKey.LabelR, TextKey.LabelG, TextKey.LabelB, TextKey.Sample3By3, TextKey.Sample5By5,
        }.ToFrozenSet();

    private static readonly FrozenDictionary<TextKey, (string English, string Korean)> s_byKey =
        Entries.ToFrozenDictionary(entry => entry.Key, entry => (entry.English, entry.Korean));

    /// <summary>
    /// The phrase for a key, or the key's own name when the table has no row for it — which the
    /// tests make sure never ships.
    /// </summary>
    public static string Lookup(TextKey key, Language language) =>
        s_byKey.TryGetValue(key, out (string English, string Korean) row)
            ? language == Language.Korean ? row.Korean : row.English
            : key.ToString();
}
